var gvjs_uT="border: 0; padding: 0; margin: 0;";gvjs_1E.prototype.tE=gvjs_B(61,function(a){this.ticks=a});gvjs_7E.prototype.tE=gvjs_B(60,function(a){gvjs_7E.o.tE.call(this,a);var b=0;gvjs_m(this.ticks,function(c){c=this.ar(c);b=Math.max(b,gvjs_qE(c/this.gK))},this);this.T7=b});
function gvjs_vT(a,b,c,d,e){gvjs_dj.call(this);this.ha=a;this.da=b;this.Oa=c;this.aL=new gvjs_zw({hb:gvjs_Vp,fontSize:d,color:gvjs_Qn,opacity:1,Ob:"",bold:!1,dd:!1,gf:!1});this.Hya=new gvjs_zw({hb:gvjs_Vp,fontSize:d,color:gvjs_7p,opacity:1,Ob:"",bold:!1,dd:!1,gf:!1});this.Ixa=new gvjs_zw({hb:gvjs_Vp,fontSize:0,color:gvjs_Qn,opacity:1,Ob:"",bold:!1,dd:!1,gf:!1});this.dva=e;this.ug=this.Ra=this.C=null;this.d1=[]}gvjs_l(gvjs_vT,gvjs_dj);
var gvjs_wT=new gvjs_1({fill:gvjs_1n,stroke:gvjs_Qn,strokeWidth:1}),gvjs_xT=new gvjs_1({fill:"#f7f7f7",stroke:gvjs_2n,strokeWidth:2}),gvjs_tja=new gvjs_1({stroke:gvjs_Sn,strokeWidth:1}),gvjs_uja=new gvjs_1({stroke:gvjs_Qn,strokeWidth:2}),gvjs_vja=new gvjs_1({fill:"#dc3912",fillOpacity:.7,stroke:"#c63310",strokeWidth:1}),gvjs_wja=new gvjs_1({fill:"#4684ee",stroke:gvjs_Sn,strokeWidth:1});gvjs_=gvjs_vT.prototype;gvjs_.Xa=NaN;gvjs_.Bb=NaN;gvjs_.kba=NaN;gvjs_.qD=NaN;gvjs_.be=0;gvjs_.CX=null;gvjs_.bL=null;
gvjs_.O3=null;gvjs_.L5=270;gvjs_.fca=0;gvjs_.eca=null;gvjs_.nJ=null;gvjs_.fz=null;gvjs_.bg=null;gvjs_.uf=function(){return this.Xa};gvjs_.vw=function(a){this.Xa=a};gvjs_.tf=function(){return this.Bb};gvjs_.eu=function(a){this.Bb=a};
gvjs_.Va=function(a,b,c){this.be=a;this.CX=b;this.lu();a=gvjs_yT(this,a);null!=this.nJ&&c?(this.bg=new gvjs_HD([this.nJ],[a],c.duration,c.easing),gvjs_I(this.bg,["begin","animate",gvjs_W],this.Pta,!1,this),gvjs_I(this.bg,gvjs_W,this.Ota,!1,this),this.bg.play(!1)):(this.nJ=a,gvjs_zT(this))};gvjs_.tE=function(a,b){this.kba=Math.max(1,a);this.qD=Math.max(1,b)};gvjs_.m2=function(a){this.fz=a};function gvjs_AT(a,b,c,d){a.d1.push({rf:b,tl:c,color:d})}gvjs_.setAnimation=function(){};
gvjs_.clear=function(){this.lu();gvjs_H(this.Ra);this.Ra=null;gvjs_$i(this)};gvjs_.draw=function(a,b){var c=new gvjs_0(this.da,this.Oa);null==this.Ra?this.Ra=new gvjs_vA(this.ha,c,a,b):this.Ra.update(c,a);this.Ra.Hp(gvjs_k(this.ro,this),a)};
gvjs_.ro=function(){var a=this.Ra.$a(),b=a.Sm(this.da,this.Oa);a.qc(b,gvjs_Rq,gvjs_ry);this.C=a;var c=this.ug=a.Qa(!1);a.appendChild(b,c);b=Math.round(.45*Math.min(this.da,this.Oa));var d=this.da/2,e=this.Oa/2;a.Pe(d-.5,e-.5,b,gvjs_wT,c);b-=gvjs_wT.Ub;b=Math.round(.9*b);a.Pe(d-.5,e-.5,b,gvjs_xT,c);b-=2*gvjs_xT.Ub;var f=.75*b;for(var g=0;g<this.d1.length;g++){var h=this.d1[g],k=gvjs_BT(this,gvjs_yT(this,h.rf)),l=gvjs_BT(this,gvjs_yT(this,h.tl)),m=new gvjs_2z,n=d+gvjs_Hx(k,b),p=e+gvjs_Ix(k,b);m.move(n,
p);m.ag(d,e,b,b,k+90,l+90,!0);n=d+gvjs_Hx(l,f);p=e+gvjs_Ix(l,f);m.wa(n,p);m.ag(d,e,f,f,l+90,k+90,!1);m.close();a.Ia(m,new gvjs_1({fill:h.color}),c)}if(this.bL||this.O3)this.bL&&(f=e-Math.round(.35*b),a.bj(this.bL,0,f,this.da,f,gvjs_U,gvjs_U,this.aL,c)),this.O3&&(f=e+Math.round(.35*b),a.bj(this.O3,0,f,this.da,f,gvjs_U,gvjs_U,this.aL,c));h=this.qD;k=.8*b;l=.9*b;n=this.kba*h;p=(this.Bb-this.Xa)/n;var q=new gvjs_2z,r=new gvjs_2z,t=this.Ixa,u=Math.round(.14*b);t.fontSize=u;for(g=0;g<=n;g++){var v=gvjs_BT(this,
gvjs_yT(this,g*p+this.Xa)),w=0==g%h,x=w?k:l;m=w?q:r;var y=d+gvjs_Hx(v,x);f=e+gvjs_Ix(v,x);m.move(y,f);y=d+gvjs_Hx(v,b);f=e+gvjs_Ix(v,b);m.wa(y,f);w&&this.fz&&(m=this.fz[Math.floor(g/h)])&&(y=d+gvjs_Hx(v,x-u/2),f=e+gvjs_Ix(v,x-u/2),x=gvjs_U,280<v||90>v?(x=gvjs_W,v=0):90<=v&&260>v?(x=gvjs_Z,v=y,y=this.da):(w=Math.min(y,this.da-y),v=y-w,y+=w,f+=Math.round(u/4)),a.bj(m,v,f,y,f,x,gvjs_U,t,c))}a.Ia(r,gvjs_tja,c);a.Ia(q,gvjs_uja,c);this.lu();this.fca=b;gvjs_zT(this);this.dva()};
gvjs_.Pta=function(a){this.nJ=a.x;gvjs_zT(this)};gvjs_.Ota=function(){this.lu()};gvjs_.lu=function(){this.bg&&(gvjs_$i(this.bg),this.bg.stop(!1),gvjs_H(this.bg),this.bg=null)};function gvjs_yT(a,b){a=(b-a.Xa)/(a.Bb-a.Xa);a=Math.max(a,-.02);return a=Math.min(a,1.02)}function gvjs_BT(a,b){return a.L5*b+gvjs_Ex((360-a.L5)/2+90)}
function gvjs_zT(a){if(a.C){var b=a.fca,c=a.C,d=a.da/2,e=a.Oa/2,f=gvjs_BT(a,a.nJ),g=Math.round(.95*b),h=Math.round(.3*b),k=gvjs_Hx(f,g);g=gvjs_Ix(f,g);var l=gvjs_Hx(f,h);h=gvjs_Ix(f,h);f=gvjs_Ex(f+90);var m=.07*b,n=gvjs_Hx(f,m);m=gvjs_Ix(f,m);f=new gvjs_2z;f.move(d+k,e+g);f.Jp(d+n,e+m,d-l+n/2,e-h+m/2,d-l,e-h);f.Jp(d-l-n/2,e-h-m/2,d-n,e-m,d+k,e+g);k=Math.round(.15*b);(g=a.eca)?c.Ac(g):g=a.eca=c.Qa();a.CX&&(b=e+Math.round(.75*b),c.bj(a.CX,0,b,a.da,b,gvjs_U,gvjs_U,a.Hya,g));c.Ia(f,gvjs_vja,g);c.Pe(d-
.5,e-.5,k,gvjs_wja,g);c.appendChild(a.ug,g)}};function gvjs_CT(a,b,c,d){this.ha=a;this.da=b;this.Oa=c;this.eO=d;this.oy=[];this.uc=[];this.fz=[];this.DX=[];this.Nq=[];this.Xa=0;this.Bb=100;this.M5=this.j1=this.AR=this.zR=this.Q4=this.gU=this.fU=this.vY=this.PO=this.OO=null;this.yr=!0;this.j0=0}gvjs_=gvjs_CT.prototype;gvjs_.qD=2;gvjs_.vw=function(a){this.Xa!=a&&(this.Xa=a,this.yr=!0)};gvjs_.uf=function(){return this.Xa};gvjs_.eu=function(a){this.Bb!=a&&(this.Bb=a,this.yr=!0)};gvjs_.tf=function(){return this.Bb};
gvjs_.setAnimation=function(a){this.M5=a};gvjs_.setValues=function(a,b,c){this.yr=this.yr||this.uc.length!=a.length||this.Nq.length!=c.length||!gvjs_cx(this.Nq,c);this.uc=a;this.DX=b;this.Nq=c};gvjs_.m2=function(a){1==a.length&&(a=["",a[0],""]);gvjs_cx(this.fz,a)||(this.fz=a,this.yr=!0)};function gvjs_DT(a,b,c){return Math.min(Math.floor(a.da/c),Math.floor(a.Oa/b))}
gvjs_.draw=function(a){if(this.yr)gvjs_xja(this,a);else for(a=0;a<this.uc.length;a++){var b=this.oy[a];b.bL=this.Nq[a];b.Va(this.uc[a],this.DX[a],this.M5)}};
function gvjs_xja(a,b){a.clear();var c=a.uc.length,d=1,e=1;if(1<c){var f=Math.floor(Math.sqrt(a.da*a.Oa/c));e=Math.floor(a.da/f);for(d=Math.floor(a.Oa/f);!(c<=Math.floor(a.da/f)*Math.floor(a.Oa/f));){var g=gvjs_DT(a,d,e+1),h=gvjs_DT(a,d+1,e);g>=h&&(f=g,e++);h>=g&&(f=h,d++)}}f=gvjs_DT(a,d,e);f-=0;h=gvjs_Fk();h.Ac(a.ha);a.oy=[];if(0!=c){var k=h.J(gvjs_6o,{style:gvjs_uT,cellpadding:0,cellspacing:0,align:gvjs_U}),l=h.J(gvjs_7o,null);h.appendChild(k,l);g=[];for(var m=0,n=0;n<d;n++){var p=h.J(gvjs_$o,{style:gvjs_uT});
h.appendChild(l,p);for(var q=0;q<e;q++){var r=h.J(gvjs_8o,{style:"border: 0; padding: 0; margin: 0; width: "+f+"px;"});g[m++]=r;h.appendChild(p,r)}}h.appendChild(a.ha,k);d=Math.round(.1*f);a.j0=0;a.yr=!0;for(e=0;e<c;e++)h=a.oy[e]=new gvjs_vT(g[e],f,f,d,gvjs_k(function(){this.j0++;this.j0==this.oy.length&&(this.yr=!1)},a)),h.vw(a.Xa),h.eu(a.Bb),h.bL=a.Nq[e],k=a.fz,l=k.length,h.tE(1<l?l-1:4,a.qD),0<l&&h.m2(k),h.Va(a.uc[e],a.DX[e],null),null!=a.OO&&null!=a.PO&&gvjs_AT(h,a.OO,a.PO,a.vY),null!=a.fU&&null!=
a.gU&&gvjs_AT(h,a.fU,a.gU,a.Q4),null!=a.zR&&null!=a.AR&&gvjs_AT(h,a.zR,a.AR,a.j1),h.draw(b,a.eO)}}gvjs_.clear=function(){for(var a=0;a<this.oy.length;++a)this.oy[a].clear();this.oy=[]};function gvjs_ET(a){gvjs_dz.call(this,a);this.G=gvjs_Fk()}gvjs_l(gvjs_ET,gvjs_dz);gvjs_=gvjs_ET.prototype;gvjs_.da=0;gvjs_.Oa=0;gvjs_.eO=!0;
gvjs_.gg=function(a,b,c){var d=new gvjs__d([c||{}]);c=this.container;var e=this.Sa(d),f=this.getHeight(d),g=gvjs_s(d,gvjs_1r);if(e!=this.da||f!=this.Oa||g!=this.eO)this.IK&&this.IK.clear(),this.IK=new gvjs_CT(c,e,f,g),this.da=e,this.Oa=f,this.eO=g;c=this.IK;e=gvjs_t(d,gvjs_qt,0);c.vw(e);e=gvjs_t(d,gvjs_ht,100);c.eu(e);e=d.ea("majorTicks",[String(c.uf()),"","","",String(c.tf())]);c.m2(e);e=gvjs_t(d,"minorTicks",2);c.qD!=e&&(c.qD=e,c.yr=!0);e=d.Ca("greenFrom");f=d.Ca("greenTo");g=d.Ca("yellowFrom");
var h=d.Ca("yellowTo"),k=d.Ca("redFrom"),l=d.Ca("redTo"),m=gvjs_Mw(d,"greenColor",gvjs_On),n=gvjs_Mw(d,"yellowColor",gvjs_Zn),p=gvjs_Mw(d,"redColor",gvjs_Yn);if(c.OO!=e||c.PO!=f||c.vY!=m||c.fU!=g||c.gU!=h||c.Q4!=n||c.zR!=k||c.AR!=l||c.j1!=p)c.OO=e,c.PO=f,c.vY=m,c.fU=g,c.gU=h,c.Q4=n,c.zR=k,c.AR=l,c.j1=p,c.yr=!0;d=gvjs_lK(d,400,gvjs_Hs);c.setAnimation(d);d=[];e=[];f=[];if(2==b.$()&&b.Y(0)==gvjs_d&&b.Y(1)==gvjs_c)for(g=0;g<b.ca();g++)null!=b.getValue(g,0)&&null!=b.getValue(g,1)&&(f.push(b.getValue(g,
0)),d.push(b.getValue(g,1)),e.push(b.Na(g,1)));else for(h=0;h<b.$();h++)if(b.Y(h)==gvjs_c)for(g=0;g<b.ca();g++)null!=b.getValue(g,h)&&(d.push(b.getValue(g,h)),e.push(b.Na(g,h)),f.push(b.Fa(h)));c.setValues(d,e,f);c.draw(a);gvjs_K(this,gvjs_x,null)};gvjs_.kf=function(){this.IK&&this.IK.clear()};gvjs_g(gvjs_2f,gvjs_ET,void 0);gvjs_ET.prototype.draw=gvjs_ET.prototype.draw;gvjs_ET.prototype.clearChart=gvjs_ET.prototype.Qb;gvjs_ET.prototype.getContainer=gvjs_ET.prototype.getContainer;
